#!/bin/bash
set -e

echo "Setup for the API labo..."
echo "Static App URL: $STATIC_APP"
echo "Dynamic App URL: $DYNAMIC_APP"

php /var/apache2/template/config-template.php > /etc/apache2/sites-available/001-reverse-proxy.conf

service apache2 reload
service apache2 restart


#rm -f /var/run/apache2/apache2.pid
#exec apache2 -DFOREGROUND